on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name:    Build the library and run tests
    steps:
      - name:  Install Doxygen
        run:   sudo apt install -y doxygen
        shell: bash
      - name:  Install the latest available LLVM toolchain
        run:   wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 20 all
        shell: bash
      - name:  Install the latest CMake - Add Kitware archive
        run:   wget https://apt.kitware.com/kitware-archive.sh && chmod +x kitware-archive.sh && sudo ./kitware-archive.sh
        shell: bash
      - name:  Install the latest CMake - Install
        run:   sudo apt update && sudo apt install cmake -y && cmake --version && /usr/bin/cmake --version
        shell: bash
      - name: Checkout the project
        uses: actions/checkout@v4.2.2
      - name: Init CPM.cmake
        run:  git submodule update --init --recursive
      - name:  Configure the project with CMake
        run:   mkdir build && CC=clang-20 CXX=clang++-20 /usr/bin/cmake . -B build -GNinja -DCMAKE_CXX_FLAGS='-stdlib=libc++ -Wall -Wextra -pedantic' -DDXX_SELFTEST=ON -DDXX_WITH_HTTP=ON -DDXX_DOXYGEN=ON -DCMAKE_EXPERIMENTAL_CXX_IMPORT_STD='d0edc3af-4c50-42ea-a356-e2862fe7a444'
        shell: bash
      - name:  Build the project
        run:   /usr/bin/cmake --build build
        shell: bash
      - name:  Run selftest
        run:   ./build/selftest
        shell: bash
      - name:  Generate docs (dummy)
        run:   /usr/bin/cmake --build build --target docs
        shell: bash
      - name:  Checkout gh-pages
        run:   git worktree add ../gh-pages origin/gh-pages
        shell: bash
      - name:  Copy generated documentation
        run:   rm -rf ../gh-pages/* && cp -R build/html/* ../gh-pages
        shell: bash
      - name:  Upload the new version of pages
        run:   cd ../gh-pages && git add -A && git commit -m "Auto-update" && git push origin gh-pages
        shell: bash
